#!/usr/bin/env python
import re
import waflib.extras.autowaf as autowaf
import waflib.Utils as Utils

def options(opt):
    pass

def configure(conf):
    autowaf.check_pkg(conf, 'lv2', atleast_version='1.0.0',
                      uselib_store='LV2_1_0_0')
    autowaf.check_pkg(conf, 'cairo', uselib_store='CAIRO', atleast_version='1.12.0')
    autowaf.check_pkg(conf, 'sndfile', uselib_store='SNDFILE')

def build(bld):
    bundle = 'a-sampler.lv2'
    module_pat = re.sub('^lib', '', bld.env.cshlib_PATTERN)
    module_ext = module_pat[module_pat.rfind('.'):]

    # Build RDF files
    for i in ['manifest.ttl', 'a-sampler.ttl']:
        obj = bld(features='subst')
        obj.source = i + '.in'
        obj.target = '../../LV2/%s/%s' % (bundle, i)
        obj.install_path = '${LV2DIR}/%s' % bundle
        obj.chmod = Utils.O644
        obj.LIB_EXT = module_ext

    # Build plugin library
    obj = bld(features     = 'c cshlib',
              source       = 'a-sampler.c',
              name         = 'a-sampler',
              cflags       = [ bld.env['compiler_flags_dict']['pic'],
                               bld.env['compiler_flags_dict']['c99'] ],
              includes     = [ '../../ardour', '../shared' ],
              target       = '../../LV2/%s/a-sampler' % bundle,
              install_path = '${LV2DIR}/%s' % bundle,
              uselib       = ['CAIRO', 'SNDFILE'],
              use          = 'LV2_1_0_0',
              )
    obj.env.cshlib_PATTERN = module_pat

# vi:set ts=4 sw=4 et:
